---
abstract: 'Ukigumo test runner server'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0
  Module::Build::Pluggable::GithubMeta: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ukigumo-Agent
provides: {}
requires:
  Amon2: 3.76
  Amon2::Plugin::ShareDir: 0
  Data::Validator: 0
  File::ShareDir: 0
  MRO::Compat: 0
  Plack: 0.9949
  Text::Xslate: 0
  Time::Duration: 0
  Twiggy: 0
  Ukigumo::Client: 0.15
  parent: 0
resources:
  bugtracker: https://github.com/ukigumo/Ukigumo-Agent/issues
  homepage: https://github.com/ukigumo/Ukigumo-Agent
  repository: git://github.com/ukigumo/Ukigumo-Agent.git
version: 0.0.7
